sudo: false

services:
  - docker

language: bash

before_install:
  - docker -v

script:
  - docker build -t "rcswain/appium:latest" --build-arg BASE_IMAGE=$BASE_IMAGE --build-arg SDK_VERSION=$SDK_VERSION --build-arg ANDROID_BUILD_TOOLS_VERSION=$ANDROID_BUILD_TOOLS_VERSION --build-arg APPIUM_VERSION=$APPIUM_VERSION --build-arg ATD_VERSION=$ATD_VERSION -f Appium/Dockerfile Appium
  - docker run --rm -v $PWD/Appium/tests:/root/tests "appium/appium:latest" bash tests/run-bats.sh
  - docker images

after_success:
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ "$TRAVIS_TAG" != "" ]]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag "rcswain/appium:latest" "rcswain/appium:$TRAVIS_TAG" && docker push "rcswain/appium:$TRAVIS_TAG" && docker push "rcswain/appium:latest";
    fi
