name: appium docker android

on:
  workflow_dispatch:
    inputs:
      tag:
        description: image tag version
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      tag: ${{ github.event.inputs.tag }}
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}


    steps:
      - uses: actions/checkout@v2

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: rcswain/appium
          tags: ${{ env.tag }}, latest
          registry: docker.io
          dockerfile: Appium/Dockerfile
          username: ${{ env.username }}
          password: ${{ env.password }}
          buildArgs: SDK_VERSION=31.0.0, ANDROID_PLATFORM_VERSION=android-31, APPIUM_VERSION=1.22.0, ATD_VERSION=1.2